//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.30 at 01:24:47 AM CST 
//


package com.isbndb.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.isbndb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Notes_QNAME = new QName("", "Notes");
    private final static QName _AuthorsText_QNAME = new QName("", "AuthorsText");
    private final static QName _TitleLong_QNAME = new QName("", "TitleLong");
    private final static QName _Title_QNAME = new QName("", "Title");
    private final static QName _Summary_QNAME = new QName("", "Summary");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.isbndb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PublisherText }
     * 
     */
    public PublisherText createPublisherText() {
        return new PublisherText();
    }

    /**
     * Create an instance of {@link BookData }
     * 
     */
    public BookData createBookData() {
        return new BookData();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link Prices }
     * 
     */
    public Prices createPrices() {
        return new Prices();
    }

    /**
     * Create an instance of {@link UrlsText }
     * 
     */
    public UrlsText createUrlsText() {
        return new UrlsText();
    }

    /**
     * Create an instance of {@link BookList }
     * 
     */
    public BookList createBookList() {
        return new BookList();
    }

    /**
     * Create an instance of {@link ISBNdb }
     * 
     */
    public ISBNdb createISBNdb() {
        return new ISBNdb();
    }

    /**
     * Create an instance of {@link AwardsText }
     * 
     */
    public AwardsText createAwardsText() {
        return new AwardsText();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notes")
    public JAXBElement<String> createNotes(String value) {
        return new JAXBElement<String>(_Notes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuthorsText")
    public JAXBElement<String> createAuthorsText(String value) {
        return new JAXBElement<String>(_AuthorsText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitleLong")
    public JAXBElement<String> createTitleLong(String value) {
        return new JAXBElement<String>(_TitleLong_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Summary")
    public JAXBElement<String> createSummary(String value) {
        return new JAXBElement<String>(_Summary_QNAME, String.class, null, value);
    }

}
